# Generated by Django 2.1.5 on 2020-06-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcamp_candidate',
            name='Contact',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
