# Generated by Django 2.1.5 on 2020-06-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_bootcamp_candidate_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcamp_candidate',
            name='EmailId',
            field=models.EmailField(default='abc', max_length=254),
            preserve_default=False,
        ),
    ]
